name: Demo1

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_ENV: 'Environment variable for demo1'
    steps:
      - name: List_job
        run: echo '${{ toJSON(job)}}'
      - name: List_runner
        run: echo '${{ toJSON(runner)}}'
      - name: List_ENV
        run: echo '${{ toJSON(env)}}'
      - name: List_github
        run: echo '${{ toJSON(github)}}'
